version: '3.3'
services:

  postgres_backend_api:
    image: postgres:12-alpine
    container_name: db_postgres
    env_file: .env
    ports:
      - 5432:5432

  pgAdmin:
    image: dpage/pgadmin4:4.22
    container_name: pgAdmin
    depends_on:
      - postgres_backend_api
    ports:
      - 16555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@mail.ru
      PGADMIN_DEFAULT_PASSWORD: developer
    logging:
      driver: none
